#!/bin/bash

#defining variables
nerdfontsrepo='https://api.github.com/repos/ryanoasis/nerd-fonts'
aFontInstalled="False"
keepArchives="False"
distDir="$HOME/.local/share/fonts"
downDir="$HOME/Downloads/NerdFonts"

# help message
usage() {
    echo "getNF: A Better way to install NerdFonts"
    echo ""
    echo "Usage:"
    echo "-h print this help message and exit"
    echo "-k Keep the downloaded archives"
    echo ""
}

# setting flags
while getopts :hk option; do
    case "${option}" in
        h) usage && exit 0 ;;
        k) keepArchives="True" ;;
        *) usage && exit 0
    esac
done

# Check if the distDir exists, if it doesn't, creat it
[ -e "$distDir" ] && echo "Fonts Directory exists, good" || mkdir -p $HOME/.local/share/fonts

# get font names
nerdFonts=$(curl --silent "$nerdfontsrepo/contents/patched-fonts?ref=master" | \
  grep "name" | \
  awk -F":" '{print $2}' | \
  sed 's/["",]//g;/install\.ps1/d')

#get the latest release number from NerdFonts github repo
release=$(curl --silent "$nerdfontsrepo/releases/latest" | \
  grep -Po '"tag_name": "\K.*?(?=")')

# use fzf to select the fonts to be installed
listFonts=$(printf '%s\n' "${nerdFonts[@]}" | fzf -m)

#loop over the selected fonts in listFonts, download and install them
for i in $listFonts; do
		checkFont=$(fc-list | grep -i "$i")
		if [ -z "$checkFont" ]; then #If the font already is installed, skip it
				echo "$i font download started" &&
						#download the font
						curl -LJO -\# "https://github.com/ryanoasis/nerd-fonts/releases/download/$release/$i.zip" \
						     -o $i.zip --output-dir "$downDir" --create-dirs &&
						echo "$i font download finished" &&
						echo "$i font unziping started" &&
						#Unzipe the downloaded archive
						unzip -qq $downDir/$i.zip -d $distDir &&
						echo "$i font unzipping finished" &&
						echo "Font $i Installed" &&
						echo "$i provides:" &&
						installedFontName=$(curl --silent "$nerdfontsrepo/contents/patched-fonts/$i/Regular/complete?ref=master" | \
									grep ".ttf" | \
									awk -F ":" 'FNR == 1 {print $2}' | \
									awk '{print $1}' | \
								        sed 's/"//g') &&
						fc-list | grep -i $installedFontName | \
						    awk -F "/" '{print $7}' | \
						    sed 's/style\=//' |  \
						    awk -F ":" 'BEGIN {print "FONT NAME" " | " "FILE NAME" " | " "STYLE"} {print $2 " | " $1 " | " $3}' | \
						    column -s "|" -t -o "|" &&
						#set this variable to true so that the font cache get's updated
						aFontInstalled=True
		else
		    echo "Font $i already installed"
		fi
done

# If a font was installed, Update the cach and remove the archive
if [ "$aFontInstalled" = "True" ]; then
		fc-cache -fv >/dev/null 2>&1 && echo "fc-chache: succeeded"
		#check if the user hasn't chooen to keep the updated, if not, remove them
		if [ "$keepArchives" = "False" ]; then
				rm $downDir/*.zip
		else
				echo "The archive files are in $downDir"
		fi
fi

echo "done"
