ARG BASE_VERSION=44
FROM fedora:${BASE_VERSION}
RUN sed -i 's/^tsflags=nodocs/#tsflags=nodocs/' /etc/dnf/dnf.conf
RUN dnf update -y && \
    dnf install -y \
    sudo vim curl fzf fontconfig xz \
    man-db man-pages rpmlint
ARG SEMVER
COPY ./dist/packages/getnf-${SEMVER}-1.noarch.rpm /tmp/
RUN dnf install -y /tmp/getnf-${SEMVER}-1.noarch.rpm
RUN useradd -m tester && echo "tester:pass" | chpasswd && usermod -aG wheel tester && chown -R tester:tester /home/tester
USER tester
WORKDIR /home/tester
CMD ["/bin/bash"]
