ARG BASE_VERSION=24.04
FROM ubuntu:${BASE_VERSION}
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    sudo vim curl fzf fontconfig xz-utils \
    unminimize man-db manpages less lintian && \
    yes | unminimize
ARG SEMVER
COPY ./dist/packages/getnf_${SEMVER}_all.deb /tmp/
RUN apt-get update && apt-get install -y /tmp/getnf_${SEMVER}_all.deb
RUN useradd -m tester && echo "tester:pass" | chpasswd && usermod -aG sudo tester && chown -R tester:tester /home/tester
USER tester
WORKDIR /home/tester
CMD ["/bin/bash"]
